### ISSUE TITLE
Add support for Redis 6.0 username auth

### ISSUE THREAD

**Issue by halidm** [Nordix/eredis#35]
In some clouds and with Redis 6.0, authentication requires an additional `username` field to grant access.

The message format is:
```
AUTH <username> <password>
```

In your current implementation, there are additional `" "` added around the password field making it impossible to use `[{password, "<username> <password"}]` in opts field in config files.

Suggested quick fix:
```
authenticate(_Socket, _TransportType, <<>>) ->
    ok;
authenticate(Socket, TransportType, Password) ->
    do_sync_command(Socket, TransportType, ["AUTH", " \"", Password, "\"\r\n"]).
```
-- would become:
```
authenticate(_Socket, _TransportType, <<>>) ->
    ok;
authenticate(Socket, TransportType, Password) ->
    do_sync_command(Socket, TransportType, ["AUTH", "  ", Password, "\r\n"]).
```

**Comment by bjosv** [comment]
Good catch, we will look into this

**Comment by zuiderkwast** [comment]
The suggested solution seems like a hack. What if the username or the password contains `"` characters?

I think we should add `{username, Username}` to the configuration and use proper Redis protocol encoding of the AUTH command, like `eredis:to_bulk/1` does for any command. (Maybe we have to export `to_bulk` or move it to another module.)
