### ISSUE TITLE
socket receiving logic in `eredis_client` could be optimized

### ISSUE THREAD

**Issue by e-kmisk** [Nordix/eredis#67]
# Problem

Right now after every received packet, `setopts(Socket, {active, once})` is called. This results in high CPU load as there can be lots of incoming packets and from performance metrics we see that `erts_internal:port_control` NIF is taking a large slice of CPU time.
```
****** Process <0.2064.0>    -- 99.98 % of profiled time *** 
FUNCTION                           CALLS        %    TIME  [uS / CALLS]
--------                           -----  -------    ----  [----------]
eredis_client:handle_call/3        17866     0.70    4546  [      0.25]
gen_server:try_dispatch/3          17866     0.71    4612  [      0.26]
erlang:port_get_data/1             17866     0.72    4676  [      0.26]
inet_tcp:send/2                    17866     0.75    4843  [      0.27]
eredis_client:safe_reply/2         17866     0.80    5181  [      0.29]
eredis_client:setopts/3            17866     0.88    5662  [      0.32]
queue:out/1                        17866     0.90    5783  [      0.32]
gen_server:handle_common_reply/8   17866     0.98    6302  [      0.35]
queue:in/2                         17866     1.00    6458  [      0.36]
prim_inet:encode_opt_val/1         17866     1.11    7185  [      0.40]
erlang:port_command/3              17866     1.27    8194  [      0.46]
inet_db:lookup_socket/1            17866     1.29    8338  [      0.47]
eredis_parser:parse/2              17866     1.31    8435  [      0.47]
gen_server:try_handle_call/4       17866     1.41    9100  [      0.51]
erlang:setelement/3                35732     1.44    9298  [      0.26]
eredis_parser:return/2             17866     1.44    9301  [      0.52]
inet:setopts/2                     17866     1.45    9360  [      0.52]
prim_inet:send/3                   17866     1.46    9393  [      0.53]
prim_inet:ctl_cmd/3                17866     1.49    9630  [      0.54]
prim_inet:send_recv_reply/2        17866     1.49    9638  [      0.54]
erlang:port_control/3              17866     1.50    9658  [      0.54]
prim_inet:enc_opt_val/2            35732     1.52    9786  [      0.27]
gen_server:decode_msg/9            35732     1.70   10968  [      0.31]
inet:'-setopts/2-lc$^0/1-0-'/1     35732     1.72   11076  [      0.31]
prim_inet:setopts/2                17866     1.87   12095  [      0.68]
eredis_client:reply/2              17866     2.16   13923  [      0.78]
gen_server:try_dispatch/4          17866     2.33   15042  [      0.84]
eredis_client:handle_info/2        17866     2.47   15933  [      0.89]
eredis_parser:do_parse/2           35732     2.78   17935  [      0.50]
gen_server:handle_msg/6            35732     2.97   19199  [      0.54]
eredis_client:handle_response/2    17866     3.13   20231  [      1.13]
eredis_client:do_request/3         17866     3.17   20440  [      1.14]
gen_tcp:send/2                     17866     3.98   25683  [      1.44]
eredis_parser:split_by_newline/2   17866     4.78   30868  [      1.73]
gen_server:reply/2                 17866     5.51   35590  [      1.99]
binary:match/2                     17866     7.23   46642  [      2.61]
gen_server:loop/7                  35732     7.50   48433  [      1.36]
erts_internal:port_control/3       17866     9.91   63994  [      3.58]
erts_internal:port_command/3       17866    11.17   72107  [      4.04]
--------------------------------  ------  -------  ------  [----------]
Total:                            821836  100.00%  645538  [      0.79]
```

# Suggestion

**Always** set socket to passive mode (`{active, false}`) during connection setup (including TLS handshake, DB cmd, Auth cmd), regardless of user-provided socket option. This is what the current code expects anyway.
Then, make the `{active, _}` receive behavior of the `eredis_client` gen_server configurable via the existing `socket_options` configuration parameter:
* if no `{active, _}` is provided in user-provided `socket_options`, then pick an ideal default behavior
  * TBD: should default behavior be the current one, ie. `{active, once}` or `{active, SomeDefaultNumber}` ?
* if  `{active, false}`  is provided, crash
  * passive receiving doesn't really make sense
* if `{active, true}` is provided:
  * after a successful connection setup, set the state to `{active, true}`
  *  in `handle_msg`, do not call `setopts` at all (leave the socket as active)
  * TBD: would there be any difference in connection reset/close handling?
* if `{active, N} where N > 0` is provided:
  * check if transport layer supports it (maybe `ssl` below OTP/21 doesn't?)
    * if not, crash?
  * store the value of `N` in the `#state{}`, ~and also store a counter of received TCP packets that starts at 0.~
  * ~on every non-error `handle_info`, increment the counter~
    * ~if the `counter >= N` then call `setopts({active, N})` again and reset counter to 0?~
  * setopt when we receive `tcp_passive` or `ssl_passive`, which we don't get if we're in {active, once} mode

These are a bit tricky because the `{active, _}` tuple from the initial `socket_options` proplist will need some special handling. `eredis_sub` should also be given consideration (at least so that it doesn't break) as it uses `eredis_client:connect` too.

**Comment by zuiderkwast** [comment]
Comparing this to cowboy. They're using active N with default N=100, but N is configurable in [options](https://ninenines.eu/docs/en/cowboy/2.9/manual/cowboy_http2/):

> **active_n (100)**
>
> The number of packets Cowboy will request from the socket at once. This can be used to tweak the performance of the server. Higher values reduce the number of times Cowboy need to request more packets from the port driver at the expense of potentially higher memory being used.

**Comment by e-kmisk** [comment]
> What's the use case of making it configurable?

Performance tuning as you show with cowboy. I was thinking that different options can be tested in a real environment to see what works best. That's easier if it is not hardcoded. 

> active_n (100)

I don't know if `active` is better or this one. This one is not technically a socket option accepted by gen_tcp/ssl so it'd need to go into the top-level options I suppose. In case `active_n` is added though, the `{active, _}` should not be explicitly discarded from the user-provided in `socket_options` because the client's logic regarding it would not be customizable through that flag.

> For {active, N} we shouldn't, but we need to setopt when we receive tcp_passive or ssl_passive, which we don't get if we're in {active, once} mode. We don't need to count the number of messages.

Ok, this sounds better then than what I thought.

**Comment by e-kmisk** [comment]
Personally I prefer using `socket_options` -> `{active, _}` for this because the code will anyway have to check what is provided there by the library user, so there's not much benefit to introducing another flag elsewhere too.
