### ISSUE TITLE
Compile issues with Elixir 1.15

### ISSUE THREAD

**Issue by anthonator** [Nordix/eredis#79]
When compiling with Elixir 1.15 we currently get the following error:

```
==> eredis
Compiling 6 files (.erl)
src/eredis_parser.erl:25:14: can't find include lib "eunit/include/eunit.hrl"
%   25| -include_lib("eunit/include/eunit.hrl").
%     |              ^
```

When setting `:prune_code_paths` to `false` in `mix.exs` it fixes the issue but according to the [release notes](https://github.com/elixir-lang/elixir/releases/tag/v1.15.0) for Elixir 1.15.0 doing this may cause runtime bugs that only occur inside a `mix release`.

We are using Elixir 1.15.2 and Erlang 26.0.2.

**Comment by zuiderkwast** [comment]
Interesting. I can't see that eunit is used in this file so maybe we can just delete that line.

But what would we need to do otherwise? List eunit as a dependency in the app file?

**Comment by anthonator** [comment]
I'm not super familiar with Erlang and rebar3 so I'm not sure what would need to happen to fix it. I did remove the reference to eunit in `eredis_parser.erl` and I was able to get it to compile without warnings in my project.

I opened #80 to fix this issue.
